### ISSUE TITLE
Dynamically loading type from Contracts assembly breaks the matching types inheritance

### ISSUE THREAD

**Issue by godrose** [natemcmaster/DotNetCorePlugins#132] opened 2020-03-22 14:35 UTC
**Describe the bug**
Dynamically loading type from Contracts assembly breaks the matching types inheritance

**To Reproduce**
1. Using this version of the library '1.2.0'
2. Run the test `ResolveContract_AssembliesAreLoadedUsingCustomLoader_ImplementationsAreRegistered`
at
`https://github.com/godrose/Solid/tree/feat-assembly-load`

**Expected behavior**
The functionality should work as outlined in the successful test
`ResolveContract_AssembliesAreLoadedUsingRegularLoader_ImplementationsAreRegistered`
at
`https://github.com/godrose/Solid/tree/feat-assembly-load`

**Comment by natemcmaster** [comment] 2020-03-27 15:15
You're talking about the test in https://github.com/godrose/Solid/commit/6cc2560c01dcce5efe3ea464c505ec0aa660fc14, right? This doesn't appear to be using 
DotNetCorePlugins. https://github.com/godrose/Solid has a lot of code that I don't understand. Can you show me a simplified version of what's going on?

**Comment by godrose** [comment] 2020-03-30 05:35
@natemcmaster Sure.
Let me explain what's going on here.
The `CustomAssemblySourceProvider` allows to load assemblies from the given root path while filtering the candidates by their prefix or namespace.
It inherits from `AssemblySourceProviderBase` abstract class which is actually responsible for loading these assemblies from the file system:
```
public abstract class AssemblySourceProviderBase : IAssemblySourceProvider
    {
        private readonly string _rootPath;
        private readonly string[] _prefixes;
        private IAssemblyLoadingStrategy _assemblyLoadingStrategy;

        /// <summary>
        /// Initializes a new instance of the <see cref="AssemblySourceProviderBase"/> class.
        /// </summary>
        /// <param name="rootPath">The root path.</param>
        /// <param name="prefixes">The prefixes.</param>
        protected AssemblySourceProviderBase(string rootPath, string[] prefixes = null)
        {
            _rootPath = rootPath;
            _prefixes = prefixes;
        }

        private Assembly[] _inspectedAssemblies;

        /// <summary>
        /// Gets the assemblies to be inspected.
        /// </summary>
        /// <value>
        /// The assemblies to be inspected.
        /// </value>
        public IEnumerable<Assembly> Assemblies => _inspectedAssemblies ?? (_inspectedAssemblies = CreateAssemblies());

        /// <summary>
        /// Returns the list of namespaces to be looked for during assembly discovery.
        /// </summary>
        /// <returns></returns>
        protected abstract string[] ResolveNamespaces();

        private Assembly[] CreateAssemblies()
        {
            _assemblyLoadingStrategy = new FileSystemBasedAssemblyLoadingStrategy(_rootPath, _prefixes,
                ResolveNamespaces(), AssemblyLoadingManager.Extensions().ToArray());
            return _assemblyLoadingStrategy.Load().ToArray();            
        }
    }
```

The assemblies are resolved on accessing the property via this code `_inspectedAssemblies = CreateAssemblies())`

The `CreateAssemblies` method uses the `FileSystemBasedLoadingStrategy` which is one of the possible strategies for loading list of assemblies (could be pre-loaded, remote, predefined, etc.)

```
public class FileSystemBasedAssemblyLoadingStrategy : IAssemblyLoadingStrategy
    {
        private readonly string _rootPath;
        private readonly string[] _prefixes;
        private readonly string[] _namespaces;
        private readonly string[] _extensions;        

        /// <summary>
        /// Initializes a new instance of the<see cref="FileSystemBasedAssemblyLoadingStrategy"/> class.     
        /// </summary>
        /// <param name="rootPath">Root path for inspection</param>
        /// <param name="prefixes">Allowed prefixes; leave empty if all are allowed.</param>
        /// <param name="namespaces">Allowed namespaces; leave empty if all are allowed.</param>
        /// <param name="extensions">Allowed extensions; leave empty if all are allowed.</param>
        public FileSystemBasedAssemblyLoadingStrategy(
            string rootPath,            
            string[] prefixes = null,
            string[] namespaces = null,
            string[] extensions = null)
        {
            _rootPath = rootPath;
            _prefixes = prefixes;
            _namespaces = namespaces;
            _extensions = extensions;
        }

        /// <inheritdoc />
        public IEnumerable<Assembly> Load() => AssemblyLoader.LoadAssembliesFromPaths(DiscoverFilePaths());
       
        private IEnumerable<string> DiscoverFilePaths()
        {
            var patternsCalculator = new PatternsCalculator();
            var patterns = patternsCalculator.Calculate(_prefixes, _namespaces, _extensions);
            var allFiles = PlatformProvider.Current.GetFiles(_rootPath).Select(Path.GetFileName).ToArray();
            var filePaths = patterns
                .Select(k =>
                    //TODO: Consider RegEx
                    allFiles.Where(t =>
                        (k.Prefix == Consts.WildCard || t.StartsWith(k.Prefix)) && 
                        (k.Contents == Consts.WildCard || t.Contains(k.Contents)) && 
                        (k.Postfix == Consts.WildCard || t.EndsWith(k.Postfix))))
                .SelectMany(k => k);
            return filePaths;
        }
    }
```

As you can see the `FileSystemBasedLoadingStrategy` essentially applies filtering on the list of all files found at the current path and then tries to load assemblies from these files:
```
 public IEnumerable<Assembly> Load() => AssemblyLoader.LoadAssembliesFromPaths(DiscoverFilePaths());
```

The `AssemblyLoader.LoadAssembliesFromPaths` is a static method or rather `Func<IEnumerable<string>, IEnumerable<Assembly>>` which is responsible for the actual assembly loading.

Its default implementation looks like this:
```
public static class AssemblyLoader
    {
        /// <summary>
        /// Loads assemblies from their paths. Replace to have custom way of loading the assemblies.
        /// </summary>
        public static Func<IEnumerable<string>, IEnumerable<Assembly>> LoadAssembliesFromPaths { get; set; } = paths => paths.Select(k =>
        {
            try
            {
                var name = Path.GetFileNameWithoutExtension(k);
                return name == null ? null : Assembly.Load(new AssemblyName(name));
            }
            catch (Exception)
            {
                return null;
            }
        }).Where(k => k != null);
    }
```

One of the tests replaces this implementation - see this line:
`AssemblyLoader.LoadAssembliesFromPaths = DynamicLoader.LoadAssemblies;`
where `DynamicLoader` is defined as such
```
internal static class DynamicLoader
    {
        public static IEnumerable<Assembly> LoadAssemblies(IEnumerable<string> paths)
        {
            return paths.Select(path =>
                PluginLoader.CreateFromAssemblyFile(assemblyFile: Path.Combine(Directory.GetCurrentDirectory(), path), 
                    t => t.PreferSharedTypes = true
                ).LoadDefaultAssembly());
        }
    }
```

So the difference here is between calling `Assembly.LoadFrom` which requires explicit library reference and using `PluginLoader` which supports dynamic loading.

Hope this helps.
If something's missing please PM me or write here.

Thanks a bunch for your contribution anyway. It really has helped a lot already!!!

**Comment by godrose** [comment] 2020-04-08 05:36
@natemcmaster Hey there. Any thoughts?

**Comment by natemcmaster** [comment] 2020-05-08 04:32
Sorry for long delay, been taking a break from github to focus on staying healthy.

Thanks for the details. Just a guess, but I see you're calling `PluginLoader` multiple times in DynamicLoader.LoadAssemblies. If the error you are seeing has to do with sharing types between assemblies that come from different instances of `PluginLoader`, then you are probably running into #60. (Short version of that issue -- each instance of `PluginLoader` loads the plugin and its dependencies in isolated verticals. Sharing between plugins is only possible if you put shared types in the host app).

To get around this, try using one instance of `PluginLoader`, or try implementing a custom AssemblyLoadContext as documented in https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support and use a single instance of AssemblyLoadContext for all assemblies you load.

**Comment by flipdoubt** [comment] 2021-02-20 19:43
@natemcmaster, can you point to an example that shows how to use one PluginLoader to load multiple plugins? Because the constructor takes a config that requires a default assembly, I'm not sure how to reuse the same one to load multiple plugins from different directories.

**Comment by natemcmaster** [comment] 2021-03-03 23:39
@flipdoubt this is answered in the HelloWorld sample.

https://github.com/natemcmaster/DotNetCorePlugins/blob/main/samples/hello-world/HostApp/Program.cs

**Comment by natemcmaster** [comment] 2021-03-03 23:40
Also in the README file :)

https://github.com/natemcmaster/DotNetCorePlugins/blob/main/README.md#the-host

**Comment by flipdoubt** [comment] 2021-04-05 12:17
@natemcmaster, thanks and oh-ok. Maybe there is some magic inside `PluginLoader.CreateFromAssemblyFile` that reuses the previous loader, but I assumed each call to `PluginLoader.CreateFromAssemblyFile` instantiated and returned a new instance. Does the code in this example really solve the problem documented in #60?

**Comment by natemcmaster** [comment] 2021-06-14 00:36
>  I assumed each call to PluginLoader.CreateFromAssemblyFile instantiated and returned a new instance. 

Yes, that is the intended behavior. However, there may be some caching happening at the .NET runtime level to reduce duplicate copies of assemblies in memory. One of the best ways to identify whether the problem really is this library or not, I recommend trying https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support and see if you get the same behavior. Since .NET Core 3, it has become much easier to build your own dynamic loaders.

**Comment by natemcmaster** [comment] 2021-11-13 05:13
Closing as I believe the question was answered, and I don't see any follow up items remaining.

**Closed by natemcmaster** 2021-11-13 05:13 UTC
Labels: bug
