### ISSUE TITLE
Unable to load e_sqlite3.dll for Microsoft.EntityFrameworkCore.Sqlite 3.0.0

### ISSUE THREAD

**Issue by Nukepayload2** [natemcmaster/DotNetCorePlugins#84] opened 2019-10-16 02:15 UTC
**Describe the bug**
`DllNotFoundException` thrown when using a plugin that consumes `Microsoft.EntityFrameworkCore.Sqlite 3.0.0` . If I downgrade EFCore.Sqlite to 2.2.6, the plugin works fine.
```console
System.TypeInitializationException: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'
DllNotFoundException: Unable to load DLL 'e_sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

**To Reproduce**
Version: 0.3.1
Code (In the main program):
```csharp
public Assembly Load(string assemblyName)
{
    return PluginLoader.CreateFromAssemblyFile(assemblyName).LoadDefaultAssembly();
}
```
The plugin connects to a Sqlite3 database with `Microsoft.EntityFrameworkCore.Sqlite 3.0.0` and print data to `Console`. (See the screenshot for details)

**Expected behavior**
The plugin should not throw `DllNotFoundException`.

**Screenshots**
![image](https://user-images.githubusercontent.com/10798596/66881932-22221700-effb-11e9-904c-bd6707164c75.png)

**Additional context**

If I copy "e_sqlite3.dll" from "plugins\runtimes\win-x64\native\e_sqlite3.dll" to the "plugins" directory, the plugin won't throw DllNotFoundException.

**Comment by natemcmaster** [comment] 2019-10-20 18:15
Two questions:

1. Can you share the .csproj file of your plugin?
2. How are you getting files into the plugin directory? i.e. do you run `dotnet publish --output $path` or something else?

**Comment by Nukepayload2** [comment] 2019-10-22 09:12
@natemcmaster 
1. I can't share all contents of the project file because it contains sensitive information. 
```vbproj
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Design" Version="1.1.6" />
    <PackageReference Include="MSTest.TestFramework" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="northwind.sqlite3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>

```
2. `dotnet publish "ProjectFileName" -c Release` and then `xcopy` them into the "plugins" directory

**Comment by natemcmaster** [comment] 2019-10-26 00:50
Sorry, but I don't think there is anything I can do to fix this error. Under the hood, EF Core's SQLite provider uses https://github.com/ericsink/SQLitePCL.raw. The way SQLitePCLRaw.nativelibrary is [attempting to load](https://github.com/ericsink/SQLitePCL.raw/blob/a18106475289e03ed2a544f2b0a83895ee93a7af/src/SQLitePCLRaw.nativelibrary/for_netcoreapp3.cs) the "e_sqlite3.dll" library circumvents [this essential callback](https://github.com/natemcmaster/DotNetCorePlugins/blob/60db210880ceaf699257f3edaa33fd185e9893b5/src/Plugins/Loader/ManagedLoadContext.cs#L167) in `System.Runtime.Loader.AssemblyLoadContext`.

The root cause appears to be the use of `System.Runtime.InteropServices.NativeLibrary`. This doesn't account for the current `AssemblyLoadContext` or the `runtimes/$rid/native/*.dll` layout.  `System.Runtime.Loader.AssemblyDependencyResolver` might be a better library for SQLitePCLRaw to use, but I'll leave that up to @ericsink.

### Workaround
Change your plugin deployment to include a runtime identifier. `dotnet publish --runtime win-x64` should do the trick.

**Comment by ericsink** [comment] 2019-10-26 00:56
Hmmm.  This is interesting.  Thanks for tagging me in.  Not sure yet what to do about it.

**Comment by Andale-online** [comment] 2019-12-07 15:10
Your workaround isn't a workaround... The native sqlite library needs to know which architecture to use. At least 32/64bit... Run into this with shared libraries for xamarin - It's normal

**Comment by natemcmaster** [comment] 2019-12-07 23:24
You're right. Depending on your scenario, publishing the plugin using `--runtime <RID>` may not be feasible. Any other suggestions on how to workaround this?

By the way @ericsink, it seems like we've run into the "native" version of this "managed" problem: https://github.com/dotnet/coreclr/blob/v3.0.0/Documentation/design-docs/AssemblyLoadContext.ContextualReflection.md#problem. Basically, the API used by SQLite isn't aware of the context it is called from. I think we should request a feature in coreclr to make System.Runtime.InteropServices.NativeLibrary honor the current assembly loading context.

**Comment by ericsink** [comment] 2019-12-09 16:44
Hmmm.  That's good info.  I'm getting a better understanding of the problem here.

**Comment by aderderian** [comment] 2020-07-29 20:39
Any updates on this? Dead in the water on it currently.

**Comment by ericsink** [comment] 2020-07-29 21:17
No significant update yet, but let's link this issue too:  ericsink/SQLitePCL.raw#343

**Comment by natemcmaster** [comment] 2020-08-03 04:31
I believe this will be addressed in .NET 5 - see https://github.com/dotnet/runtime/issues/13819.

I'm closing as there is no action item here for this library. The problem is external to my code and something I can't fix in older versions of .NET.

**Closed by natemcmaster** 2020-08-03 04:31 UTC
Labels: external

**Comment by ravigupta0510** [comment] 2020-08-12 12:09
Hi guys,
 
I was also facing the same issue. I found the solution and it's working perfectly for me. If you ask I can write a detail note on the solution.

**Comment by emilbm** [comment] 2020-08-20 11:54
> Hi guys,
> 
> I was also facing the same issue. I found the solution and it's working perfectly for me. If you ask I can write a detail note on the solution.

Yes please....

**Comment by AndreeaFGrosu** [comment] 2022-08-24 08:47
Hi!
@jeremybytes have a blog post about this error [here](https://jeremybytes.blogspot.com/2019/01/weirdness-with-ef-core-2-sqlite-net.html).
Maybe his solution will ever help someone, although it's a "work-around".

**Comment by ptgullas** [comment] 2022-09-26 19:56
> Hi! @jeremybytes have a blog post about this error [here](https://jeremybytes.blogspot.com/2019/01/weirdness-with-ef-core-2-sqlite-net.html). Maybe his solution will ever help someone, although it's a "work-around".

Yes, his solution of manually copying the e_sqlite3.dll worked for me (I don't like it either)

**Comment by arikanhasan** [comment] 2024-09-23 13:55
I had a windows form project running in .Net 6.0. 

When I upgraded it directly to .Net 8.0.8, there was no problem working in debug, but when I published the application and installed it through setup, I encountered this error. 

After trying many solutions, I finally changed the .Net version to 7.0 and the problem was solved. 

Then when I downgraded to .Net 8.0.8 again, I didn't get the same error again. 

I guess upgrading suddenly causes some deficiencies in such version transitions.
