### ISSUE TITLE
Plugin depending on System.Drawing.Common cannot be used properly

### ISSUE THREAD

**Issue by gbrown-ce** [natemcmaster/DotNetCorePlugins#12] opened 2018-10-19 14:57 UTC
**Describe the bug**
When using the PluginLoader to load a library that references System.Drawing.Common, anytime any code executes from your plugin that uses a component from that library (PrintDocument in our case), the code blows up with an error claiming `System.Drawing is not supported on this platform.`.  Obviously that is cross platform now (and I'm running this on Windows to boot).

**To Reproduce**
1. Add a reference to System.Drawing.Common to your plugin project.
2. Write some basic functionality that uses that library (instantiating a PrintDocument is sufficient).
3. Use McMaster.NETCore.Plugins 0.2.0 in you main project
4. Load primary DLL of your plugin using PluginLoader
5. Use reflection (or whatever is easiest) to call the offending System.Drawing code
6. See the exception generated

**Expected behavior**
I would expect this code to work properly as if it weren't being loaded by a plugin

**Additional context**
As a temporary workaround, if I use the PluginLoaderOptions.PreferSharedTypes flag and reference System.Drawing.Common directly in my host project, things work properly if that helps at all.

**Comment by natemcmaster** [comment] 2018-10-20 23:54
Dang, my fix only works on macOS. I’ll have to find a Windows machine to figure out why this failed on AppVeypr.

**Comment by gbrown-ce** [comment] 2018-10-22 15:59
@natemcmaster thanks for looking into this so quickly!

Unfortunately it hasn't seemed to resolve the issue on my end.  I upgraded to 0.2.1, uninstalled System.Drawing.Common from my kernel project and turned off "PreferSharedTypes" and I still see the `System.Drawing is not supported on this platform.` error.  Maybe I'm doing something else wrong? Or have an even edgier case?

**Comment by natemcmaster** [comment] 2018-10-22 16:09
Can you share the .deps.json file from your plugin?

**Comment by gbrown-ce** [comment] 2018-10-22 16:32
Here you go:

[Phoenix.Service.Printing.deps.txt](https://github.com/natemcmaster/DotNetCorePlugins/files/2502220/Phoenix.Service.Printing.deps.txt)

**Comment by natemcmaster** [comment] 2018-10-22 16:39
Huh. Your deps.json file looks fine. What is happening is that the "lib/netstandard2.0/System.Drawing.Common.dll" file is being loaded, not the "runtimes/*/lib/netcoreapp2.0/System.Drawing.Common.dll" file. This is what changes in 0.2.1 were supposed to fix. 

The loader will still get `lib/netstandard2.0/System.Drawing.Common.dll` depending on how you prepared your plugin. If you are zipping up `bin/Release/netcoreapp2.1/`, you won't have the right files. `dotnet publish` should be used. Can you share which files are in your plugin? 

```js
 "System.Drawing.Common/4.5.1": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "2.1.0",
          "Microsoft.Win32.SystemEvents": "4.5.0"
        },
        "runtime": {
          "lib/netstandard2.0/System.Drawing.Common.dll": {  // This is being loaded.
            "assemblyVersion": "4.0.0.1",
            "fileVersion": "4.6.26919.2"
          }
        },
        "runtimeTargets": {
          "runtimes/unix/lib/netcoreapp2.0/System.Drawing.Common.dll": { // This (or runtimes/win/) should be loaded.
            "rid": "unix",
            "assetType": "runtime",
            "assemblyVersion": "4.0.0.1",
            "fileVersion": "4.6.26919.2"
          },
          "runtimes/win/lib/netcoreapp2.0/System.Drawing.Common.dll": {
            "rid": "win",
            "assetType": "runtime",
            "assemblyVersion": "4.0.0.1",
            "fileVersion": "4.6.26919.2"
          }
        },
        "compile": {
          "ref/netstandard2.0/System.Drawing.Common.dll": {}
        }
      },
```

**Comment by gbrown-ce** [comment] 2018-10-22 17:00
Yep, I am using dotnet publish for this, not just the bin directory.

Are you asking which libraries are directly referenced by the plugin? If so:

```
<PackageReference Include="AutoMapper" Version="7.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="CenterEdge.Common.Correlation.Middleware" Version="0.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.3" />
    <PackageReference Include="Phoenix.Microservice.HealthCheck" Version="0.1.1" />
    <PackageReference Include="Phoenix.Microservice.ModelBinding" Version="1.4.5" />
    <PackageReference Include="Phoenix.Microservice.Results" Version="1.4.5" />
    <PackageReference Include="Phoenix.Microservice.Swagger" Version="1.4.5" />
    <PackageReference Include="Phoenix.Microservice.UrlRewrite" Version="0.1.1" />
    <PackageReference Include="Phoenix.Microservice.Validation" Version="1.4.5" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.6.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="System.Globalization.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.3" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
    <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.5.1" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />

    <ProjectReference Include="..\CenterEdge.Printing\CenterEdge.Printing.csproj" />
```

One maybe possible issue here is the referenced project `CenterEdge.Printing` references `CenterEdge.Barcodes` which is where the `System.Drawing.Common` reference comes into play (the plugin project itself doesn't reference `System.Drawing.Common`)

**Comment by gbrown-ce** [comment] 2018-10-22 17:04
I tried adding a reference to `System.Drawing.Common` directly to my plugin project with no improvement.

**Comment by natemcmaster** [comment] 2018-10-22 17:09
I meant which files are in the plugin folder? When you are calling `PluginLoader.CreateFromAssembly(path)`, what exactly is in `path`? I'm expecting to see a "runtimes/" folder next to your "Phoenix.Service.Printing.deps.json" file with two versions of System.Drawing.Common.dll in it.

**Comment by natemcmaster** [comment] 2018-10-22 17:33
I'll re-open this. I thought I had it fixed because I was able to write this test to reproduce the error. Any chance you can help be create a minimal repro?

See https://github.com/natemcmaster/DotNetCorePlugins/blob/master/test/TestProjects/DrawingApp/DrawingApp.csproj and https://github.com/natemcmaster/DotNetCorePlugins/blob/8f5c28fa70f0869a1af2e2904536268f184e71de/test/Plugins.Tests/BasicAssemblyLoaderTests.cs#L52-L67 for my repro.

**Comment by gbrown-ce** [comment] 2018-10-22 17:37
Sure. I'll see what I can come up with.  The main difference i see from the get go is that your project is .NET Core 2.0, where mine is 2.1.  I'll mess with your repro app and see where I get.

**Comment by gbrown-ce** [comment] 2018-10-22 18:13
I ruled out the 2.1 stuff being an issue.  But I do see a significant difference in the test that you have and the real world scenario I'm using.  The test directory is not the result of a publish. It only has these files:

![image](https://user-images.githubusercontent.com/28538067/47309633-f2684b00-d602-11e8-8e7e-17967e476c7e.png)

No runtime directories, etc.

When it goes to resolve `PrintDocument` it is getting the type from `"file:///C:/Users/gbrown/.nuget/packages/system.drawing.common/4.5.1/runtimes/win/lib/netcoreapp2.0/System.Drawing.Common.dll"` which passes your check of it containing "runtimes", but maybe isn't entirely accurate.

I'm a little stuck in that I can't get this project to publish in the same way my Printing project publishes for some reason. The configuration window looks a little different and it never outputs the runtime folder, etc

**Comment by gbrown-ce** [comment] 2018-10-22 18:16
Oh, I see why the config window was different.  One is `Microsoft.NET.Sdk.Web` the other is `Microsoft.NET.Sdk`

**Comment by gbrown-ce** [comment] 2018-10-22 18:30
Oh... so here is a big difference.

Your unit test project references DrawingApp via `TestProjectRefs.targets`  I feel like that probably is having an impact on things.

**Comment by gbrown-ce** [comment] 2018-10-22 18:37
Strike that.  I nixed it from the project and just referenced the published folder and it worked still.  I'm not sure if the test isn't good enough or maybe there is just some other variable.  I'll keep digging at it and let you know.

**Comment by natemcmaster** [comment] 2018-10-23 00:39
Thanks for digging more. This one is a mystery to me.

The piece I'm interested in is what happens when this method is called and `library.Name == "System.Drawing.Common"`. You will probably have to pull in my source into your project and replace PackageRef with ProjectRef to McMaster.NETCore.Plugins so you can drop a debug point here.

https://github.com/natemcmaster/DotNetCorePlugins/blob/8f5c28fa70f0869a1af2e2904536268f184e71de/src/Plugins/Loader/ManagedLoadContext.cs#L127-L161

**Comment by gbrown-ce** [comment] 2018-10-23 11:42
Okay, so I stepped through that code and it loads `System.Drawing.Common.dll` from the main folder (peer to the plugin assembly by default.

I tried forcing it to skip that, and it then grabs it from `C:\\Users\\gbrown\\.nuget\\packages\\system.drawing.common\\4.5.1\\lib/netstandard2.0/System.Drawing.Common.dll`

That doesn't work either.

If I force it to skip that, it tries to from the peer library again in the `PlatformInformation.ManagedAssemblyExtensions` loop.  I don't see anywhere that it tries to load from the runtimes directory.

If I manually change the path in the debugger to `runtimes\win\lib\netcoreapp2.0\System.Drawing.Common.dll` it works.

**Comment by gbrown-ce** [comment] 2018-10-23 11:50
Wait... scratch all that.  I don't think I was updated 🤦‍♂️

**Comment by gbrown-ce** [comment] 2018-10-23 12:31
Nm, I was updated, just not to your last unrelated commit.  Anyway.  Stuck at the same point.

**Comment by gbrown-ce** [comment] 2018-10-23 13:09
Hmmm, another wall I just hit when trying to get it to work in the context of the test project:

```Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'```

I'm pointing your unit test directly to the plugin directory that I'm using in my application.  It bombs out like this, whereas in my application does not using the same calls (mine bombs out later when I get to drawing).  It has to to with my base probject references `Microsoft.AspNetCore.All` so it is able to cope.  If I add that to the test project, I can't get it to run the test for some reason (like it won't run at all, it doesn't fail).

All of those DLLs show up in a "refs" folder when I publish the plugin.  Maybe also of note: System.Drawing.Common _and_ System.Drawing DLLs are also in there.  So there are actually **3** copies of the Common library.  But also System.Drawing which is where I'm guessing its falling down since its complaining about System.Drawing and not System.Drawing.Common.

**Comment by natemcmaster** [comment] 2018-10-23 14:28
How can I help? I’m not sure how to reproduce the errors you’re seeing. I’d love to get to the bottom of this.

**Comment by gbrown-ce** [comment] 2018-10-23 14:51
I'm going to try to put together a plugin that mimics the problem but with less code. Then I can ship it over to you if that works.  Please stand by.

**Comment by gbrown-ce** [comment] 2018-10-23 16:00
[Phoenix.Client.ServiceTest.zip](https://github.com/natemcmaster/DotNetCorePlugins/files/2506858/Phoenix.Client.ServiceTest.zip)

I threw together the barebones needed for our host application.  appsettings.json tells it where to look to load the plugin.  So just change that into the parent directory of the unzipped plugin. The Client.Service copies everything in that directory into a subfolder under itself calls `Plugins` and then loads it.

One the service is running you can check out to make sure it is loaded properly by hitting `http://localhost:{port}/swagger/ui` in the browser.  You should see a single endpoint there called `/test/print`.  If you POST to that endpoint, it generates the `PlatformNotSupportedException`

**Comment by natemcmaster** [comment] 2018-10-24 05:37
Thanks for the repro. This helped me identify the problem.

Your host application has this property in it:
```xml
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
This makes your host application a self-contained app. I've added more details here for why this doesn't work for plugins with RID assets: https://github.com/natemcmaster/DotNetCorePlugins/issues/14

Until we can fix #14, there are basically 2 solutions:
* make System.Drawing.Common a dependency of Phoenix.Client.ServiceTest, and add any type from System.Drawing.Common to the "shared types" parameter on `PluginLoader.CreateFromAssemblyFile(string assembly, Type[] sharedTypes)`
* remove `<RuntimeIdentifier>`. This will make your app framework-dependent instead of self-contained. In framework-dependent mode, the resolution of the windows-specific version of `System.Drawing.Common.dll` should work dynamically.

**Comment by gbrown-ce** [comment] 2018-10-24 11:07
Ahhh.  That makes more sense why we couldn't see this happening in the test app.  Thanks for figuring that out. Unfortunately we're running our actual host app as as windows service, so to the best of my knowledge, having a RID is required.  So this sound like potentially a bug in .net core itself? Or do you think there is a way you can address it just in the plugin?

**Comment by natemcmaster** [comment] 2018-10-24 14:50
I don’t believe self-contained is required to run a Windows service. Framework-dependent apps should run just fine in that environment.

Regardless, we can still find a way to make the RID graph work for self-contained. It will probably mean putting a copy of the rid graph in this library. It’s not exactly a bug in .net core, just an annoying limitation.

**Comment by gbrown-ce** [comment] 2018-10-24 14:58
According to this, it is required:

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1

**Comment by nathanaw** [comment] 2018-10-24 20:34
I'm pretty sure you can run windows services framework dependent. We're doing it.

The syntax is tricky because you have to specify the path to dotnet.exe, but you can install them with SC.exe if you use the format:

`sc create "MyServiceName" binPath= "C:\Program Files\dotnet\dotnet.exe C:\path\to\my\service\foo.dll --win-service"`

(The space after the "=" is intentional.)

**Comment by natemcmaster** [comment] 2018-10-25 15:30
=> https://github.com/aspnet/Docs/issues/9214

I'm going to close this particular issue as I believe the original issue was addressed, at least for framework-dependent apps. Let's use #14 to follow up on the self-contained story. Solving this one isn't a simple hot fix -- it may involve adding new API.

**Closed by natemcmaster** 2018-10-25 15:30 UTC
Labels: bug

**Comment by gbrown-ce** [comment] 2018-10-26 16:06
@natemcmaster Unfortunately if I use that UseAppHost bit and leave out the RID, I get this error:

`NETSDK1066	A RuntimeIdentifier must be specified to publish a framework-dependent application with an application host.`

And that is using the lastest SDK.  So I think maybe I'm still stuck on that, unless I misunderstood. Its fine for the moment as the workaround works just fine.  But thought I'd let you know.

**Comment by gbrown-ce** [comment] 2018-10-26 16:15
@natemcmaster it looks like currently you need to specify a RID still when using `<UseAppHost>`.

**Comment by gbrown-ce** [comment] 2018-10-26 17:46
@nathanaw thanks for the tip! That got us over this hump.
