### ISSUE TITLE
Update plugins functionality 

### ISSUE THREAD

**Issue by masums** [natemcmaster/DotNetCorePlugins#48] opened 2019-07-10 07:06 UTC
When project will go live then it will require to update its plugins at run time like WordPress.
So I think at your library you can provide that functionality for loading new version of plugins at runtime.

**Comment by natemcmaster** [comment] 2019-07-12 20:31
I’m not 100% sure what you are asking for. Are you requesting a feature that has the ability to unload and reload a new version of the same project?

**Comment by masums** [comment] 2019-07-16 13:11
Yes, you are right. Existing plugins upgrade system at your framework. Unload running plugins and load updated version of that plugin at runtime.

**Comment by natemcmaster** [comment] 2019-07-16 18:41
Thanks for clarifying. This feature has been requested before, but I haven't had time to investigate how hard it would be to add. I would consider taking a pull request to add this feature.

Closing as duplicate of https://github.com/natemcmaster/DotNetCorePlugins/issues/37

**Closed by natemcmaster** 2019-07-16 18:41 UTC
Labels: duplicate, enhancement
