### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'e_sqlite3' or one of its dependencies

### ISSUE THREAD

**Issue by HamedFathi** [natemcmaster/DotNetCorePlugins#214] opened 2021-06-08 14:25 UTC
**Describe the bug**
I am using `Microsoft.Data.Sqlite` inside one of my plugins, below functionality.

```cs
private string[] GetSQLiteTables(string connStr)
{
    var tables = new List<string>();

    using var connection = new SqliteConnection(connStr);
    connection.Open();
    var command = connection.CreateCommand();
    command.CommandText = @"SELECT name FROM sqlite_master WHERE type ='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;";
    using var reader = command.ExecuteReader();
    while (reader.Read())
    {
        tables.Add(reader.GetString(0));
    }

    return tables.ToArray();
}
```

but when I am loading the plugin I get the following error:

```
DllNotFoundException: Unable to load DLL 'e_sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

**To Reproduce**

The project and code is [here](https://github.com/dotnet-toolbelt/Gravity/blob/3bad2e66201137268591da8063046482763d9151/Gravity.PluginLoader/Program.cs#L108)

**Expected behavior**
I think the loader should load the DLL without a problem.  Even I copied `SQLitePCLRaw.provider.e_sqlite3.dll` to the plugin folder but nothing happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/8418700/121200614-2bb55e00-c874-11eb-960d-f147c2b529fc.png)

**Comment by natemcmaster** [comment] 2021-06-09 07:12
Possibly a duplicate of https://github.com/natemcmaster/DotNetCorePlugins/issues/84. Can you read that thread? If it's the same issue, this issue isn't something we can fix here. You'll have to ask for help from Microsoft or use workarounds shared in that thread.

**Closed** 2021-06-09 07:33 UTC
Labels: bug
